apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-helm-release
  namespace: sbr-ns
spec:
  releaseName: nginx-helm-release
  chart:
    spec:
      chart: helm-nginx-chart
      sourceRef:
        kind: GitRepository
        name: helm-nginx-chart
  interval: 15m
